name: build opensource COBOL 4J

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js をインストール
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # npm dependencies をインストール
      - name: Install npm dependencies
        run: npm ci
      
      # Prettier フォーマットチェック
      - name: Check Prettier formatting
        run: npm run format:check

      - name: Install Rust
        run: rustup update stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # mdbook をインストール
      - name: Install mdbook
        run: cargo install mdbook

      # mdbook でビルド
      - name: Build mdbook
        run: mdbook build

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "src/*.md"
